# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - '7.0'
  - '7.1'

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev
  - mkdir -p build/logs

# Commands you want to run that will verify your build.
script:
  ## PHPUnit
  - phpunit -c ./ --coverage-text --coverage-clover build/logs/clover.xml

# Customize when the notification emails are sent.
notifications:
  on_success: never
  on_failure: never

# upload coverage log to coveralls
after_script:
  ## Coveralls
  - php vendor/bin/coveralls -v
